apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: dockersandheep/react-pipe:6
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://api.example.com
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app
spec:
  selector:
    app: my-react-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
